### ISSUE TITLE
Update the jetbrains-backend-coder plugin in Gateway

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/jetbrains-backend-coder#1]
Ideally, we should use Gateway to detect when a new version of the jetbrains-backend-coder plugin is available and automatically download and install this update in the IDE so that users don't have to manually check for new releases.
If Gateway does not have this capability, we will have to prompt the user to manually upgrade.

**Requirements:**
- [ ] If possible, use Gateway to automatically detect and install new plugin versions. 
- [ ] If not possible, prompt the user to manually upgrade.
- [ ] Support early-access and LTS versions as outlined in #3.
- [ ] Update our Toolbox branch for feature parity.

**Comment by code-asher** [comment]
After some internal discussion, it might be best to implement this generically, like a list of plugins that the Gateway plugin can pre-install for you.  One of those plugins could be the new backend plugin (perhaps set in there by default).

https://github.com/coder/jetbrains-coder/issues/386

Then it would be the extension basically doing `ssh -c idea.sh installPlugins coder-gateway-backend`.

**Comment by Kira-Pilot** [comment]
covered by https://github.com/coder/jetbrains-coder/issues/386
